- name: configure /boot/cmdline.txt
  lineinfile: 
    dest: /boot/cmdline.txt
    search_string: "console=serial0,115200 console=tty1 root=PARTUUID=4bcc33ea-02 rootfstype=ext4 fsck.repair=yes rootwait quiet splash plymouth.ignore-serial-consoles"
    line: "console=serial0,115200 console=tty1 root=PARTUUID=4bcc33ea-02 rootfstype=ext4 fsck.repair=yes rootwait quiet splash plymouth.ignore-serial-consoles cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory" 
    state: present
  notify:
    - reboot