---
- name: Update all packages to their latest version
  apt: name="*" state=latest
- name: Upgrade all packages
  apt: upgrade=dist force_apt_get=yes
- name: Install a list of packages
  apt:
    pkg:
    - vim
    - git
    - dnsutils
    - podman
    - apt-transport-https 
    - ca-certificates 
    - curl
- name: Remove useless packages from the cache
  apt: autoclean=yes
- name: Remove dependencies that are no longer required
  apt: autoremove=yes
